server:
  port: 9123

spring:

  main:
    allow-bean-definition-overriding: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/booking
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        order_updates: true
        order_inserts: true
        cache:
          use_query_cache: false
          use_second_level_cache: false
        show_sql: false

  kafka:
    consumer:
      bootstrap-servers: localhost:9092

  redis:
    host: localhost
    port: 6379

  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-dates-with-context-time-zone: true
      write-dates-with-zone-id: true
