version: '3.0'

services:
  postgres:
    image: postgres:14
    container_name: booking-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booking
      TZ: 'Asia/Ho_Chi_Minh'
      PGTZ: 'Asia/Ho_Chi_Minh'
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - booking-postgres:/var/lib/postgresql/data

  redis:
    container_name: booking-redis
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "true"

  zookeeper:
    container_name: booking-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: booking-kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    expose:
      - "29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      - zookeeper

volumes:
  booking-postgres:
    driver: local
